# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoArchiveIt < Formula
  desc "A lightweight archive management utility, written in Go."
  homepage "https://github.com/korbexmachina/go-archive-it/"
  version "0.0.8-1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/korbexmachina/go-archive-it/releases/download/v0.0.8-1/go-archive-it_Darwin_arm64.tar.gz"
      sha256 "fd267db76b52864d5c71b9ae35d66db23aeb1a3245a59b462c864a407da5e7c1"

      def install
        bin.install "go-archive-it"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/korbexmachina/go-archive-it/releases/download/v0.0.8-1/go-archive-it_Darwin_x86_64.tar.gz"
      sha256 "9cbd9639ea50c3570bcf49c401909d36e4538aac95b60ac55dd6a34578ad2d47"

      def install
        bin.install "go-archive-it"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/korbexmachina/go-archive-it/releases/download/v0.0.8-1/go-archive-it_Linux_x86_64.tar.gz"
      sha256 "05c13be177bb9e17b779942554d14185086dc2e7cf309b87d432938c4c9f8745"

      def install
        bin.install "go-archive-it"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/korbexmachina/go-archive-it/releases/download/v0.0.8-1/go-archive-it_Linux_arm64.tar.gz"
      sha256 "7cdd3b24a93de7250251d8a5cfb9c6a57edeed4e37956107de51ad632af09edf"

      def install
        bin.install "go-archive-it"
      end
    end
  end

  test do
    system "#{bin}/go-archive-it -h"
    # ...
  end
end
