# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roll < Formula
  desc "Roll some dice in the terminal!"
  homepage "https://github.com/korbexmachina/roll/"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.3/roll_Darwin_x86_64.tar.gz"
      sha256 "69ebd5d78b0a9febab9dc857cc2afafb2e957f943bb8b3e9992c2bae9c1327a9"

      def install
        bin.install "roll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.3/roll_Darwin_arm64.tar.gz"
      sha256 "4770541f12e857cb5eeaf78821f321fa8850ecc575feb61b48e5adaebb732a86"

      def install
        bin.install "roll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.3/roll_Linux_x86_64.tar.gz"
      sha256 "9fcd8fb66b1b07aeb3cffcea034c4ba76b50fd0cf1232173dc80941adc39fe32"

      def install
        bin.install "roll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.3/roll_Linux_arm64.tar.gz"
      sha256 "ec3d0326e190ab9b6e3fdaacddad34b3d37feca5577174a25871ea400dac565c"

      def install
        bin.install "roll"
      end
    end
  end

  test do
    system "#{bin}/roll -h"
    # ...
  end
end
