# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roll < Formula
  desc "Roll some dice in the terminal!"
  homepage "https://github.com/korbexmachina/roll/"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.2/roll_Darwin_x86_64.tar.gz"
      sha256 "0a371da476ed9adb1199a4497fce8dc7c5cfdee66679c938a9d8f55e60777dfa"

      def install
        bin.install "roll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.2/roll_Darwin_arm64.tar.gz"
      sha256 "0abb043cda864e6125392b0283795b348632393c159b16b6d928d620c2f4daaf"

      def install
        bin.install "roll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.2/roll_Linux_x86_64.tar.gz"
      sha256 "945b174cd997d69b39d96971ac6053c0e8b3bcf8380c6bbea287248e2b841914"

      def install
        bin.install "roll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/korbexmachina/roll/releases/download/v0.0.2/roll_Linux_arm64.tar.gz"
      sha256 "9010bcbfaa82140f03f16475c1ecf8fb47d56c09e35a2563a2bd816d6ecce62f"

      def install
        bin.install "roll"
      end
    end
  end

  test do
    system "#{bin}/roll -h"
    # ...
  end
end
